version: "2"
services:
  es:
    build:
      context: "es/."
    command: /sbin/init
    container_name: es
    privileged: true
    volumes:
      - "~/.data/es/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
  head:
    build:
      context: "head/."
    container_name: head
    depends_on:
      - es
    ports:
      - "9100:9100"
